version: '1.0'

services:
  api:
    build: ./backend
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
 
    environment:
      - POSTGRES_DB=${PSQL_DB_NAME}
      - POSTGRES_USER=${PSQL_USERNAME}
      - POSTGRES_PASSWORD=${PSQL_PW}
    volumes:
      - postgres_data:/var/lib/postgresql/data
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5433

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
